services:
  - type: web
    name: movie-recommender
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 2 -b 0.0.0.0:$PORT api:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: TMDB_API_KEY
        value: 973eac1c6ee5c0af02fd6281ff2bb30b
